# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.B_numeraire_Call <- function(n_steps, S, K, sigma, r, T) {
    .Call(`_KWAENFInR_B_numeraire_Call`, n_steps, S, K, sigma, r, T)
}

parallelVectorSum <- function(x) {
    .Call(`_KWAENFInR_parallelVectorSum`, x)
}

